stages:
    - build
    - push
    - clean

build:
    stage: build
    script:
        - docker build -t nbis:$CI_PIPELINE_ID .

push:
    stage: push
    only:
        - master
    script:
        - docker tag nbis:$CI_PIPELINE_ID ${REGISTRY}/nbis 
        - docker push ${REGISTRY}/nbis

temporary:
    stage: clean
    
    script:
        - docker rmi -f nbis:$CI_PIPELINE_ID

registry:
    stage: clean
    only:
        - master
    
    script:
        - docker rmi -f ${REGISTRY}/nbis
